### ISSUE TITLE
JSON To Struct function retaining values from previous calls in loops.

### ISSUE THREAD

**Issue by Datura359** [dirkfist/JsonToStructWiki#2]
![image](https://user-images.githubusercontent.com/48599792/101721534-2e2a2d00-3a76-11eb-8a8b-24e6465ac8c4.png)
In the example above, I've created an array of JSON strings and I'm looping through them and inputting the JSON data into the JSON to Struct function.  The structure I'm using contains only a boolean and a float to keep things simple.   The default values in the structure are "false" for the boolean and 0.0 for the float.  To test that the function is working, I'm printing out the values that are stored in the newly created structure.

Upon execution, one would expect the following output based upon the supplied JSON being input (chronologically):
false
0.0
true
0.3
false
2.3
false
0.0
false 
0.0

When executing however, the following is output (again chronologically, with errors **bolded**):
false
0.0
true
0.3
**true**
2.3
false
**2.3**
false
**2.3**

When there were errors, the specific value was not defined in the JSON, indicating that the JSON to Struct function is reusing values from previous calls in the loop rather than using the default values for the field.    This behaviour does not appear to happen with separate calls outside of loops, so if I were to call a JSON to Struct function and input some values, and then call another afterwards through a different button or key press, but using the same structure, there's no issue.

I have a feeling this is a bug as I believe each call through a loop should always provide either the value as defined in the JSON supplied, or if not available in the JSON, the default value from the structure, not from previous calls.

**Comment by dirkfist** [comment]
This is a bug, At this time I'm a bit busy, and don't have the project set up

**Comment by dirkfist** [comment]
Issue does not impact parsing a packaged array.
![ArrayStruct](https://user-images.githubusercontent.com/3104075/107890872-281a5780-6ed0-11eb-86e3-30d47177cdce.png)

**Comment by dirkfist** [comment]
The problem is that you are writing into the same Object each time
![ForEachItem](https://user-images.githubusercontent.com/3104075/107891467-b3491c80-6ed3-11eb-8f99-02547fb9703e.png)

**Comment by dirkfist** [comment]
![ForEachItem2](https://user-images.githubusercontent.com/3104075/107894347-32dee780-6ee4-11eb-926e-d809c81c1a76.png)

**Comment by dirkfist** [comment]
Fixed !
