### ISSUE TITLE
UE 4.26 Update Required

### ISSUE THREAD

**Issue by Datura359** [dirkfist/JsonToStructWiki#3]
Small bit of code needs to change in order to make JSON to Struct compatible with UE4.26:

/Source/json2struct/Private/JsonAsyncNode.cpp Line 22:
	TSharedPtr<IHttpRequest> Request = Http->CreateRequest();

Needs to read:
	TSharedPtr<IHttpRequest,ESPMode::ThreadSafe> Request = Http->CreateRequest();

**Comment by dirkfist** [comment]
I'm not planning on working on this, this week

**Comment by PdVortex** [comment]
Any update on this small change to support 4.26?

**Comment by dirkfist** [comment]
I have a day job and I want to fix an issue with default values, and the issue with enums. Also compiling a plugin requires a full source build of the engine.

**Comment by PdVortex** [comment]
As do I. 
Corrected it in the source code and compiled it in a new project and then moved the files back into the marketplace plugin folder, this has allowed me to use it in version UE4 4.26.1
